# copy of our compose-dev.yaml file

services:
  agencia:
    build: .
    image: austin-dev-image # simply names the image that is being built
    container_name: austin-dev-container
    # volumes: .:/agencia